### ISSUE TITLE
Force Reset Button does not confirm

### ISSUE THREAD

**Issue by gronke** [CentauriSolutions/EyeDP#141]
The "Reset" account button in an administrators view does not give feedback to the administrator whether the action was performed or not. Because accidentally clicking it multiple times would issue (and invalidate) multiple reset token, this action should be performed after a confirmation from the admin. At the same time the UI should show whether a mail was successfully sent or not.

**Comment by ChrisMacNaughton** [comment]
Adding confirmation should be fairly easy and reasonable; however, the email is actually sent asynchronously, so the web response is returned before the email is actually sent
