### ISSUE TITLE
cannot add Yubikey based TOTP based 2FA

### ISSUE THREAD

**Issue by igalic** [CentauriSolutions/EyeDP#145]
Yubikeys allow generating TOTP based tokens: https://developers.yubico.com/OATH/
together with their authenticator app: https://developers.yubico.com/OATH/YubiKey_OATH_software.html

I tested the ["Working Example"](https://github.com/mdp/rotp#working-example) of the underlying library rotp, and *it works™*

That means that the parameters with which we call rotp are too much for Yubikeys to take.

- Could we fix that, or would we very much weaken security?
- How can i test the parameters? I'm not seeing how EyeDP calls rotp.

**Comment by ChrisMacNaughton** [comment]
EyeDP calls ROTP indirectly via [devise-two-factor](https://github.com/tinfoil/devise-two-factor/blob/f3e40dc3ae5c26e42228d55d8df57cefab8eb167/lib/devise_two_factor/models/two_factor_authenticatable.rb#L45), and I don't see that doing anything strange either :-/
