### ISSUE TITLE
Timeoutable should be configurable by an admin

### ISSUE THREAD

**Issue by ChrisMacNaughton** [CentauriSolutions/EyeDP#196]

**Comment by gronke** [comment]
In addition to that, please consider restoring the "Remember Me" feature. As a user I would expect an increased session expiration window.

**Comment by ChrisMacNaughton** [comment]
As long as there is a desire to timeout a User session on inactivity, I can't see a way to have a Remember me feature that works, that doesn't completely negate the session timeout. The issue that I see with combining these two features is that, by the nature of Remember me, it allows renewing a session that's expired without further action by the user. When combined with timing out a session for inactivity, Remember me overrides it allowing a user to sty logged in after being inactive for up to two weeks!

**Comment by ChrisMacNaughton** [comment]
I'm going to split the ability to disable Timeoutable into a new issue( #237)

**Comment by ChrisMacNaughton** [comment]
Incidentally, it looks like Devise agrees that combining these is a bit weird, as there's code in Devise to not Timeout a User if Remember is active: https://github.com/heartcombo/devise/commit/b97b3e6e3b570324467ac84d807111837943ec20
