### ISSUE TITLE
The settings page should generate and display the sha1 of the saml certificate

### ISSUE THREAD

**Issue by ChrisMacNaughton** [CentauriSolutions/EyeDP#53]
`openssl x509 -noout -fingerprint -sha1 -inform pem -in myCert.crt`

**Comment by igalic** [comment]
does SAML not support any… better fingerprinting in certificates?

**Comment by ChrisMacNaughton** [comment]
The SHA1 (or other versions) are sometimes (it's not required) used for verification purposes with SAML service providers. I can easily expand this to cover other hash algorithms as well as needed
