### ISSUE TITLE
tell user what's going on if he's not authorized for anything

### ISSUE THREAD

**Issue by sinteur** [CentauriSolutions/EyeDP#73]
since "you're already logged on" is a bit sparse

**Comment by ChrisMacNaughton** [comment]
This should actually be handled by Nginx as EyeDP returns either a 401 (Unauthorized) or a 403 (Forbidden) depending on if a user is not logged in, or doesn't have permissions to access the requested resource [[1]](https://github.com/CentauriSolutions/EyeDP/blob/0cae5e8e8736b120acab336faa2eb48806f76fa6/app/controllers/basic_auth_controller.rb#L17-L22).
