### ISSUE TITLE
It should propegate 2fa status through SAML

### ISSUE THREAD

**Issue by ChrisMacNaughton** [CentauriSolutions/EyeDP#97]

**Comment by ChrisMacNaughton** [comment]
As this is a very research-laden question, I'm deferring this from the 1.0 but it should be viable as a point release as it's just a new assertion

**Comment by ChrisMacNaughton** [comment]
https://docs.gitlab.com/ee/integration/saml.html#bypass-two-factor-authentication

**Comment by igalic** [comment]
what about other software, that isn't gitlab?

**Comment by ChrisMacNaughton** [comment]
The thing that I was trying to capture on that page was actually that "In addition to the changes in GitLab, make sure that your IdP is returning the AuthnContext. For example: "

```xml
<saml:AuthnStatement>
    <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:MediumStrongCertificateProtectedTransport</saml:AuthnContextClassRef>
    </saml:AuthnContext>
</saml:AuthnStatement>
```

**Comment by ChrisMacNaughton** [comment]
I [separated the OIDC feature](#186) out as I'm not sure that there's a spec for this currently and I wanted to implement this for SAML
